test: &test
  adapter: mysql2
  encoding: utf8
  database: <%= ENV.fetch('PT_CI_DATABASE', 'paper_trail') %>_test
  pool: 5
  username: <%= ENV.fetch('PT_CI_DB_USER', 'root') %>
  host: <%= ENV.fetch('PT_CI_DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('PT_CI_DB_PORT', 3306) %>
  protocol: TCP

  # password deliberately blank
  password:
